// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package ttnpb

var RxMetadataFieldPathsNested = []string{
	"advanced",
	"antenna_index",
	"channel_index",
	"channel_rssi",
	"downlink_path_constraint",
	"encrypted_fine_timestamp",
	"encrypted_fine_timestamp_key_id",
	"fine_timestamp",
	"frequency_offset",
	"location",
	"location.accuracy",
	"location.altitude",
	"location.latitude",
	"location.longitude",
	"location.source",
	"rssi",
	"rssi_standard_deviation",
	"signal_rssi",
	"snr",
	"source",
	"source.gateway_ids",
	"source.gateway_ids.eui",
	"source.gateway_ids.gateway_id",
	"source.packet_broker",
	"source.packet_broker.forwarder_id",
	"source.packet_broker.forwarder_net_id",
	"source.packet_broker.forwarder_tenant_id",
	"source.packet_broker.home_network_net_id",
	"source.packet_broker.home_network_tenant_id",
	"source.packet_broker.hops",
	"source.packet_broker.message_id",
	"time",
	"timestamp",
	"uplink_token",
}

var RxMetadataFieldPathsTopLevel = []string{
	"advanced",
	"antenna_index",
	"channel_index",
	"channel_rssi",
	"downlink_path_constraint",
	"encrypted_fine_timestamp",
	"encrypted_fine_timestamp_key_id",
	"fine_timestamp",
	"frequency_offset",
	"location",
	"rssi",
	"rssi_standard_deviation",
	"signal_rssi",
	"snr",
	"source",
	"time",
	"timestamp",
	"uplink_token",
}
var LocationFieldPathsNested = []string{
	"accuracy",
	"altitude",
	"latitude",
	"longitude",
	"source",
}

var LocationFieldPathsTopLevel = []string{
	"accuracy",
	"altitude",
	"latitude",
	"longitude",
	"source",
}
var PacketBrokerMetadataFieldPathsNested = []string{
	"forwarder_id",
	"forwarder_net_id",
	"forwarder_tenant_id",
	"home_network_net_id",
	"home_network_tenant_id",
	"hops",
	"message_id",
}

var PacketBrokerMetadataFieldPathsTopLevel = []string{
	"forwarder_id",
	"forwarder_net_id",
	"forwarder_tenant_id",
	"home_network_net_id",
	"home_network_tenant_id",
	"hops",
	"message_id",
}
var PacketBrokerRouteHopFieldPathsNested = []string{
	"received_at",
	"receiver_agent",
	"receiver_name",
	"sender_address",
	"sender_name",
}

var PacketBrokerRouteHopFieldPathsTopLevel = []string{
	"received_at",
	"receiver_agent",
	"receiver_name",
	"sender_address",
	"sender_name",
}
